# -*- coding: utf-8 -*-
"""Untitled45.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDepso8IgVvyeQ92T1OAJdp43wSyeALw

# Import required libraries for data analysis and statistics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

plt.style.use("default")

# Load the advertising and digital marketing datasets
ads = pd.read_csv("advertising.csv")
digital = pd.read_csv("digital_marketing.csv")

ads.head(), digital.head()

import pandas as pd

ads = pd.read_csv("advertising.csv")
digital = pd.read_csv("digital_marketing.csv")
# Inspect column names of both datasets
print(ads.columns)
print(digital.columns)

# Display info and descriptive statistics for the advertising dataset
print("Advertising dataset info:")
print(ads.info())
print(ads.describe())
# Display info and descriptive statistics for the digital marketing dataset
print("\nDigital dataset info:")
print(digital.info())
print(digital.describe())

# Remove missing values and duplicate rows from both datasets
ads = ads.dropna().drop_duplicates()
digital = digital.dropna().drop_duplicates()

# Drop unnecessary index-like column if it exists
if "Unnamed: 0" in ads.columns:
    ads = ads.drop(columns=["Unnamed: 0"])

# Create an ID column in both datasets and merge them into a single dataframe
ads["id"] = range(len(ads))
digital["id"] = range(len(digital))

df = pd.merge(ads, digital, on="id")
# Display the first rows of the merged dataframe
df.head()



# Plot histograms for key numeric variables to explore their distributions
import pandas as pd
import matplotlib.pyplot as plt

# Re-load and preprocess data to define df, as it was not defined
ads = pd.read_csv("advertising.csv")
digital = pd.read_csv("digital_marketing.csv")

ads = ads.dropna().drop_duplicates()
digital = digital.dropna().drop_duplicates()

if "Unnamed: 0" in ads.columns:
    ads = ads.drop(columns=["Unnamed: 0"])

ads["id"] = range(len(ads))
digital["id"] = range(len(digital))

df = pd.merge(ads, digital, on="id")

numeric_cols = [
    "TV Ad Budget ($)",
    "Radio Ad Budget ($)",
    "Newspaper Ad Budget ($)",
    "Sales ($)",
    "Clicks",
    "Impressions",
    "Engagement_Score",
    "Conversion_Rate",
    "Acquisition_Cost",
    "ROI"
]

df[numeric_cols].hist(bins=15, figsize=(14, 10))
plt.tight_layout()
plt.show()



# Scatter plot to visualize the relationship between TV Ad Budget and Sales
plt.scatter(df["TV Ad Budget ($)"], df["Sales ($)"])
plt.xlabel("TV Ad Budget ($)")
plt.ylabel("Sales ($)")
plt.title("TV Budget vs Sales")
plt.show()

# Scatter plot to visualize the relationship between Engagement Score and Sales
plt.scatter(df["Engagement_Score"], df["Sales ($)"])
plt.xlabel("Engagement Score")
plt.ylabel("Sales ($)")
plt.title("Engagement Score vs Sales")
plt.show()

# Scatter plot to visualize the relationship between Clicks and Sales
plt.scatter(df["Clicks"], df["Sales ($)"])
plt.xlabel("Clicks")
plt.ylabel("Sales ($)")
plt.title("Clicks vs Sales")
plt.show()



# Clean Acquisition_Cost by removing currency symbols and converting to float
df['Acquisition_Cost'] = df['Acquisition_Cost'].replace({r'[$,]': ''}, regex=True).astype(float)

# Compute and visualize the correlation matrix for selected numeric variables
corr_cols = [
    "TV Ad Budget ($)",
    "Radio Ad Budget ($)",
    "Newspaper Ad Budget ($)",
    "Sales ($)",
    "Clicks",
    "Impressions",
    "Engagement_Score",
    "Conversion_Rate",
    "Acquisition_Cost",
    "ROI"
]

corr = df[corr_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


ads = pd.read_csv("/content/advertising.csv")
digital = pd.read_csv("/content/digital_marketing.csv")

ads = ads.dropna().drop_duplicates()
digital = digital.dropna().drop_duplicates()

if "Unnamed: 0" in ads.columns:
    ads = ads.drop(columns=["Unnamed: 0"])

ads["id"] = range(len(ads))
digital["id"] = range(len(digital))

df = pd.merge(ads, digital, on="id")

# 1) Sales Boxplot
plt.figure(figsize=(6,4))
sns.boxplot(x=df["Sales ($)"], color="skyblue")
plt.title("Boxplot of Sales ($)")
plt.xlabel("Sales ($)")
plt.tight_layout()
plt.show()

# 2) Engagement Score Boxplot
plt.figure(figsize=(6,4))
sns.boxplot(x=df["Engagement_Score"], color="orange")
plt.title("Boxplot of Engagement Score")
plt.xlabel("Engagement Score")
plt.tight_layout()
plt.show()

# 3) ROI Boxplot
plt.figure(figsize=(6,4))
sns.boxplot(x=df["ROI"], color="lightgreen")
plt.title("Boxplot of ROI")
plt.xlabel("ROI")
plt.tight_layout()
plt.show()


df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values("Date")

# Create a daily time series of total Sales and plot it
ts_daily = df.groupby("Date")["Sales ($)"].sum().reset_index()

plt.figure(figsize=(12, 5))
plt.plot(ts_daily["Date"], ts_daily["Sales ($)"])
plt.xlabel("Date")
plt.ylabel("Total Sales ($)")
plt.title("Daily Sales Time Series")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Set Date as index and create a weekly time series of total Sales
df_ts = df.set_index("Date")

# Weekly total Sales
ts_weekly = df_ts["Sales ($)"].resample("W").sum()

plt.figure(figsize=(12, 5))
plt.plot(ts_weekly.index, ts_weekly.values)
plt.xlabel("Week")
plt.ylabel("Total Weekly Sales ($)")
plt.title("Weekly Sales Time Series")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Compute and plot a 7-day rolling mean to smooth daily Sales fluctuations
ts_daily = df.groupby("Date")["Sales ($)"].sum().reset_index()
ts_daily["Sales_7d_roll"] = ts_daily["Sales ($)"].rolling(window=7, min_periods=1).mean()

plt.figure(figsize=(12, 5))
plt.plot(ts_daily["Date"], ts_daily["Sales ($)"], alpha=0.4, label="Daily Sales")
plt.plot(ts_daily["Date"], ts_daily["Sales_7d_roll"], linewidth=2, label="7-day Rolling Mean")
plt.xlabel("Date")
plt.ylabel("Sales ($)")
plt.title("Daily Sales with 7-day Rolling Average")
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# Create and plot weekly average ROI as a time series
ts_roi_weekly = df_ts["ROI"].resample("W").mean()

plt.figure(figsize=(12, 5))
plt.plot(ts_roi_weekly.index, ts_roi_weekly.values)
plt.xlabel("Week")
plt.ylabel("Average ROI")
plt.title("Weekly Average ROI Time Series")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# Create regression plots (scatter + regression line) for selected features vs Sales
import seaborn as sns
import matplotlib.pyplot as plt

features = [
    "TV Ad Budget ($)",
    "Radio Ad Budget ($)",
    "Newspaper Ad Budget ($)",
    "Clicks",
    "Impressions",
    "Engagement_Score"
]

for col in features:
    plt.figure(figsize=(6, 4))
    sns.regplot(
        x=col,
        y="Sales ($)",
        data=df,
        scatter_kws={'alpha': 0.5},
        line_kws={'color': 'red'}   # regression line color
    )
    plt.title(f"Sales vs {col}")
    plt.tight_layout()
    plt.show()



from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Select features for the regression model
# If you don't have "Digital_Spend" as a column, remove that line
X = df[[
    "TV Ad Budget ($)",
    "Radio Ad Budget ($)",
    "Newspaper Ad Budget ($)"
    # , "Digital_Spend"  # uncomment if exists in your dataframe
]]

y = df["Sales ($)"]

# Train–test split for model evaluation
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit the regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)

# Compute evaluation metrics
r2  = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("Regression Model Performance on Test Set")
print(f"R²   : {r2:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")

# Optional: check coefficients to see feature influence
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
}).sort_values(by="Coefficient", ascending=False)

print("\n Feature Influence (Regression Coefficients):")
print(coef_df)



# Perform a t-test comparing Sales between high and low engagement groups

# Split the dataset into High and Low engagement groups based on the median

import numpy as np
from scipy import stats

median_eng = df["Engagement_Score"].median()
df["eng_group"] = np.where(df["Engagement_Score"] >= median_eng, "High", "Low")

high_sales = df[df["eng_group"] == "High"]["Sales ($)"]
low_sales = df[df["eng_group"] == "Low"]["Sales ($)"]

t_stat, p_two = stats.ttest_ind(high_sales, low_sales, equal_var=False)

p_one = p_two/2 if t_stat > 0 else 1 - p_two/2

print("t statistic:", t_stat)
print("two-sided p-value:", p_two)
print("one-sided p-value (High > Low):", p_one)

